version: 2.1
executors:
  java-executor:
    docker:
      - image: openjdk:11

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Compile and Test
          command: |
            javac SimpleApp.java
            java SimpleApp
            git config --global user.email "vincebufete@gmail.com"
            git config --global user.name "JediMuffin"
            git add .  # Add all changes to the staging area
            git commit -m "Your commit message here"
            git fetch origin  # Fetch the latest changes from the remote repository
            git pull origin main  # Pull the latest changes from the main branch
            git push origin circleci-project-setup:main

                        
 
