version: 2.1
executors:
  java-executor:
    docker:
      - image: openjdk:11

jobs:
deploy:
   steps:  
     - checkout
     - run:
          name: Push Changes
          command: |
            git config --global user.email "vincebufete@gmail.com"
            git config --global user.name "JediMuffin"
            git add -A
            git commit -m "Auto-commit from CircleCI"
            git push origin main
