version: 2.1
executors:
  java-executor:
    docker:
      - image: openjdk:11

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Compile and Test
          command: |
            javac SimpleApp.java
            java SimpleApp
            
 workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - deploy:
          name: Deploy to GitHub
          requires:
            - build
          steps:
            - attach_workspace:
                at: /workspace
            - run:
                name: Commit and Push Changes
                command: |
                  git config --global user.email "vincebufete@gmail.com"
                  git config --global user.name "JediMuffin"
                  git add .
                  git commit -m "Automated commit by JediMuffin"
                  git push origin main
