version: 2.1
executors:
  java-executor:
    docker:
      - image: openjdk:11

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Compile and Test
          command: |
            javac SimpleApp.java
            java SimpleApp
   deploy:
    executor: default-executor
    steps:
      - attach_workspace:
          at: /CICD_DEMO
      - run:
          name: Deploy to Main Branch
          command: |
            git config user.email vincebufete@gmail.com"
            git config user.name "JediMuffin
            git checkout -f main
            git commit --allow-empty -m "Automatic commit from CircleCI [skip ci]"
            git push -u origin main
