version: 2.1
executors:
  java-executor:
    docker:
      - image: openjdk:11

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Compile and Test
          command: |
            javac SimpleApp.java
            java SimpleApp
            git config --global user.email "vincebufete@gmail.com"
            git config --global user.name "JediMuffin"
            git checkout main
            git pull origin main
            git checkout circleci-project-setup
            git pull origin circleci-project-setup
            git checkout main
            git merge circleci-project-setup
            git push origin main

                        
 
