version: 2.1
executors:
  java-executor:
    docker:
      - image: openjdk:11

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Compile and Test
          command: |
            javac SimpleApp.java
            java SimpleApp
  deploy:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Deploy to Windows Directory
          command: |
            mkdir -p C:\Temp\JavaApp
            cp SimpleApp.class C:\Temp\JavaApp\
