version: 2.1
executors:
  default-executor:
    docker:
      - image: circleci/php:7.4

jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install --no-progress --no-suggest

      - run:
          name: Run tests
          command: phpunit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
