
version: 2.1

# Define a job to be invoked later in a workflow.

jobs:
  build:

    docker:
      - image: circleci/php:7.4

    steps:
      - checkout
      - run:
           - run:
          	name: Run tests
          	command: phpunit

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
